### ISSUE TITLE
Add Search

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#1]
~WP Rest seems to have a search endpoint we can take advantage of~

* Search index exists using Webpack Compiler (can this be improved)?
* Add a React hook that can be used throughout the application to make quick searches
* Add Fuse.js for fuzzy search
* Add clientside search to homepage

**Comment by doingandlearning** [comment]
Though if you're going to statically build the site I'm guessing this is less relevant?

**Comment by colbyfayock** [comment]
@doingandlearning yeah - i forgot to follow up on my comment here.

i think i talked to you about this? haha but id love to get your feedback on this:

https://github.com/colbyfayock/next-wordpress-starter/blob/master/plugins/search-index.js

the implementation isn't done yet - but i created that plugin that compiles a json file from the wordpress posts API that allows you to create a little index of titles and slugs, that way you can do a clientside search off of that index

the compiled search files i in public/search.json

first time writing a webpack plugin 😅  so id be curious about how i did with taht

also wondering what all might be missing that would be expected of wordpress

i think Pages for one. maybe i can make the search tunable using a config object, so people can decide whether or not it includes certain things in the index
