### ISSUE TITLE
Debug option at plugins

### ISSUE THREAD

**Issue by GuilleAngulo** [colbyfayock/next-wordpress-starter#100]
Just an idea:

Currently the plugins have 4 lines of console log each if everything goes without any errors:
```
[SearchIndex] Compiling file public/wp-search.json
[SearchIndex] Successfully fetched posts from http://xxxxxxxxx/graphql
[SearchIndex] Created directory ./public
[SearchIndex] Successfully wrote file to public/wp-search.json
```
Making a total of 12 lines if all plugins are passed. I was thinking that maybe is a good idea to just log 1 line (per plugin) if everthing goes as supossed, something like: `Successfully created: wp-search.json`. 

In order to not lose all the useful console logs, we can grab a new boolean variable debug at each plugin:

`const { env, outputDirectory, outputName, debug = false } = nextConfig;`

And set all console logs with an && operator based on that debug variable. 

`debug && console.log('....')`

Like so, by default only one line is logged (a new final log added after plugin.postcreate, not conditional). The errors will still work as they are handle as `throw new Error`. Also in case is needed, we can pass the variable **debug = true** at `next.config.js` and activate all the logs accross the code.

![shot](https://user-images.githubusercontent.com/50624358/100519475-d8e94400-3176-11eb-8100-7933ada2e266.png)

What do you think?

**Comment by colbyfayock** [comment]
yup i think that makes sense for sure

do you think theres a way to tie that into something like a verbose flag (--verbose)? or is it more common to include a debug property like that?

**Comment by GuilleAngulo** [comment]
@colbyfayock Not sure about it. I was checking some [plugins](https://github.com/vercel/next-plugins), but I didnt find an example for a verbose case... I would say that for this case, following next-compose-plugins [configuration structure](https://github.com/vercel/next-plugins), passing a custom variable inside config seems like a good option (I agree that verbose would be a more accurate naming). Also because I'm not sure how would work to pass an inline argument like the --verbose (as a command line) in this case..

Another concern: Should the rest of errors (at `util.js` mostly) be converted to **throw error** instead of a log? Because if something has an error the console wont output anything.

**Comment by colbyfayock** [comment]
yeah if there's already an existing standard for plugins i think that makes sense

as far as util.js goes, i think that makes sense as well
so for instance, were you thinking instead of:
```
} catch (e) {
    console.log(`[${process}] Failed to fetch posts from ${apolloClient.link.options.uri}: ${e}`);
```
you may do this?
```
} catch (e) {
    throw new Error((`[${process}] Failed to fetch posts from ${apolloClient.link.options.uri}: ${e}`);
```

**Comment by GuilleAngulo** [comment]
Exactly. I can take care of this one if you like the idea

**Comment by colbyfayock** [comment]
yup sounds great, thanks
