### ISSUE TITLE
Option for AMP Support Needed [Feature]

### ISSUE THREAD

**Issue by arpitmittaldev** [colbyfayock/next-wordpress-starter#111]

**Comment by colbyfayock** [comment]
hey @arpitmittaldev can you give me an idea of what the requirements are to support AMP?

**Comment by colbyfayock** [comment]
@arpitmittaldev any thoughts? otherwise i'll close this until we have more information

**Comment by arpitmittaldev** [comment]
@colbyfayock , It would be great if there can be some option to turn on/off the AMP pages according the user's interest.

Amp configuration includes making changes to the HTML tags.

Example:

`<!DOCTYPE html>
<html ⚡>
  <head>
    <meta charset="utf-8" />
    <title>Sample document</title>
    <link rel="canonical" href="./regular-html-version.html" />
    <meta
      name="viewport"
      content="width=device-width,minimum-scale=1,initial-scale=1"
    />
    <style amp-custom>
      h1 {
        color: red;
      }
    </style>
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "NewsArticle",
        "headline": "Article headline",
        "image": ["thumbnail1.jpg"],
        "datePublished": "2015-02-05T08:00:00+08:00"
      }
    </script>
    <script
      async
      custom-element="amp-carousel"
      src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"
    ></script>
    <script
      async
      custom-element="amp-ad"
      src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"
    ></script>
    <style amp-boilerplate>
      body {
        -webkit-animation: -amp-start 8s steps(1, end) 0s 1 normal both;
        -moz-animation: -amp-start 8s steps(1, end) 0s 1 normal both;
        -ms-animation: -amp-start 8s steps(1, end) 0s 1 normal both;
        animation: -amp-start 8s steps(1, end) 0s 1 normal both;
      }
      @-webkit-keyframes -amp-start {
        from {
          visibility: hidden;
        }
        to {
          visibility: visible;
        }
      }
      @-moz-keyframes -amp-start {
        from {
          visibility: hidden;
        }
        to {
          visibility: visible;
        }
      }
      @-ms-keyframes -amp-start {
        from {
          visibility: hidden;
        }
        to {
          visibility: visible;
        }
      }
      @-o-keyframes -amp-start {
        from {
          visibility: hidden;
        }
        to {
          visibility: visible;
        }
      }
      @keyframes -amp-start {
        from {
          visibility: hidden;
        }
        to {
          visibility: visible;
        }
      }
    </style>
    <noscript
      ><style amp-boilerplate>
        body {
          -webkit-animation: none;
          -moz-animation: none;
          -ms-animation: none;
          animation: none;
        }
      </style></noscript
    >
    <script async src="https://cdn.ampproject.org/v0.js"></script>
  </head>
  <body>
    <h1>Sample document</h1>
    <p>
      Some text
      <amp-img src="sample.jpg" width="300" height="300"></amp-img>
    </p>
    <amp-ad
      width="300"
      height="250"
      type="a9"
      data-aax_size="300x250"
      data-aax_pubname="test123"
      data-aax_src="302"
    >
    </amp-ad>
  </body>
</html>
`


Documentation: https://amp.dev/documentation/examples/introduction/hello_world/?format=websites
Templates: https://amp.dev/documentation/templates/?format=websites

**Comment by colbyfayock** [comment]
thanks for the idea @arpitmittaldev i think this would probably be prioritized lower than some of the other work in the Issues backlog

I'm also not totally sure how we would approach  this, we would first need to parse the HTML which we're currently not doing, in order to render the `<amp-img` and such, as right now the content of posts and pages come from wordpress as string. that's something that i plan on working on at some point but it'll take a bit of work

id love to see if there are clean examples of doing this in Next.js if that's available
