### ISSUE TITLE
Safari Invalid Date

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#116]
I noticed that in Safari, when going particularly to a Post page, the page fails to render due to an Invalid Date issue.

Looks like in the GraphQL query, the `modified` date doesn't return in a correct format 

When querying for `modified` it comes as:
```
2021-01-24 02:34:18
```
Which is invalid when adding to a `new Date()` instance.

But what's needed is 
```
2021-01-24T02:34:18
```
Which is available inside of `modifiedGmt`

is this a WPGraphQL issue? expected?

**Comment by colbyfayock** [comment]
Created an issue for WPGraphQL to check out https://github.com/wp-graphql/wp-graphql/issues/1696

**Comment by thedavedavies** [comment]
Just spotted this issue in the wild on a project I'm working on. I just updated my query to `modifiedGmt` which fixes it (as you found out too). Is that enough to fix it in the project?

**Comment by colbyfayock** [comment]
hey! yeah i think i tried that on spacejelly.dev too. feel free to make a PR if you'd like, otherwise im on vaca for a few days :)

**Comment by thedavedavies** [comment]
Nice one. I've updated the graphQL fields to `modifiedGmt` which were crashing the single posts on Safari, leaving the `modified` graphQL fields everywhere else for now, because that seems to work fine. I'll submit a PR for this.

**Comment by colbyfayock** [comment]
Fixed by #123
