### ISSUE TITLE
Related Posts

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#117]
Could we do a simple implementation of "related posts"?

A basic idea could be loading more posts from the category of the active post

They could be added at the bottom of the page. More from [category]

**Comment by GuilleAngulo** [comment]
hey @colbyfayock I was thinking on this one and I think I have an implementation. Not sure if you are already working on it... if not, happy to send a PR 😃 

Looks like this:

![related-posts](https://user-images.githubusercontent.com/50624358/106282153-f4c4a100-621e-11eb-844a-884d35a06678.png)

**Comment by colbyfayock** [comment]
that looks good to me! maybe a little extra spacing above the header to separate it similar to the "last updated" line from the original content

but yeah, go ahead with a PR!

**Comment by GuilleAngulo** [comment]
Perfect! Making that change, and sending the PR 💪
