### ISSUE TITLE
WordPress Plugin support

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#12]
Ideally the starter could easily support common plugins

How can we provide opt-in support to things like ACF without adding a bunch of code right into the starter? can we?

**Comment by Locheed** [comment]
For the ACF you need https://github.com/wp-graphql/wp-graphql-acf then it's just another query to get ACF fields to NextJS.

**Comment by colbyfayock** [comment]
Yoast SEO plugin support via https://github.com/colbyfayock/next-wordpress-starter/pull/149

**Comment by colbyfayock** [comment]
don't think there is really anything additional that needs to be done with ACF as kind of alluded to above with it just being added to a query, and there's nothing really that would be baked in like Yoast, so probably not necessary

closing this and will instead open as people have ideas for plugin-specific implementations
