### ISSUE TITLE
Add excerpt to RSS if available

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#125]
We should add the excerpt if it's available as the Content of the RSS feed to serve as a blurb for the feed item

![image](https://user-images.githubusercontent.com/1045274/107134864-d700d700-68c3-11eb-8284-4b95ac2b0116.png)

**Comment by GuilleAngulo** [comment]
Oops my fault. Good catch. It is implemented in the creation of the feed (description field at `generateFeed()`), but forgot to include the excerpt field at the GraphQL query on `getAllPosts()` 🤦‍♂️ . I'll send the PR to fix it
