### ISSUE TITLE
Page 404

### ISSUE THREAD

**Issue by GuilleAngulo** [colbyfayock/next-wordpress-starter#133]
## Description
Currently there isn't a custom 404 page and when landing at a page that doesn't exist, the default message is "An unexpected error has occurred.". In Next.js creating a custom 404 page is as easy as creating a `pages/404.js` file , so I thought it would be a nice adition. Anytime trying to access a page that doesn't exist, it will fall to that page.

About the content it could be a simple message like **Page Not Found** and a link to go back to homepage? What do you think?

**Comment by colbyfayock** [comment]
yeah i think that makes sense! good call

are any other error pages common? i guess it's not server-side, so there really shouldn't be any other "error" pages

**Comment by GuilleAngulo** [comment]
Exactly, this 404 is statically generated. Next provides another option of custom errors at `pages/_error.js` but these rely on server-side: https://nextjs.org/docs/advanced-features/custom-error-page#customizing-the-error-page

I'm trying to find out why currently is throwing that _An unexpected error has occurred._ on non-existing pages, because Next has a default 404 page ...

**Comment by colbyfayock** [comment]
could it be due to using `fallback: false,`? i would still expect nextjs to provide a 404 instead but im not 100% sure of the details of that properly

**Comment by GuilleAngulo** [comment]
So according to the doc: `If fallback is false, then any paths not returned by getStaticPaths will result in a 404 page.` In other projects i'm getting the default 404 correctly ... strange

![page404](https://user-images.githubusercontent.com/50624358/109010078-1e41e280-768e-11eb-99ee-147796484984.png)

Creating the 404.js file seems to solve this issue. Even in the case of having the default 404 I thought that by having a custom one would be a good idea in order to wrap the error with the `Layout` that allows navigation (header and footer), and also providing a quick link to go back.

**Comment by colbyfayock** [comment]
yeah thats really weird... i'd be curious to know why but at least it resolves it 🤷

**Comment by GuilleAngulo** [comment]
I think I found the reason. According to the [doc](https://nextjs.org/docs/advanced-features/automatic-static-optimization): `If you have a custom App with getInitialProps then this optimization will be turned off in pages without Static Generation.`. So as the custom _app is now using the `getInitialProps` the Automatic Static Optimization is turned off. Made a test taking off the `getInitialProps` and the 404 is working properly.

**Comment by colbyfayock** [comment]
ahh interesting okay. well good to know

as much as i love the unopinionated data layer, i wish there was a better opinionated mechanism for global data fetching like that
