### ISSUE TITLE
Category - TypeError: Cannot destructure property `name` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by TheDictator** [colbyfayock/next-wordpress-starter#142]
TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at getStaticProps (webpack-internal:///./src/pages/posts/[slug].js:378:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)

The posts in WP all have multiple categories and tags so I am not sure what could be causing this. The posts load fine on category and index pages, but throw this error when visiting post entry pages when it is trying to access the categories on a post object.

Any ideas on how to fix this query?

Thank you.

**Comment by colbyfayock** [comment]
hey @TheDictator do i have a codesandbox or GitHub repo I can look at?

**Comment by TheDictator** [comment]
Added you to the repo

**Comment by colbyfayock** [comment]
@TheDictator the code works with my instance of wordpress, can you share your graphql URL you're using to load wordpress?

**Comment by colbyfayock** [comment]
closing since i haven't heard back, let me know if you're still running into any issues
