### ISSUE TITLE
Date fields

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#15]
Add date fields like created and last edited to posts

**Comment by doingandlearning** [comment]
Great idea - these are available on the REST API.

Is this adding these to the post template or to the search.json or both?

**Comment by colbyfayock** [comment]
I added the Date field to the post list and the post page.

We probably only want to add the Last Edited to the Post Page, not on the homepage or archive list

we also want to definitely include these in the search index created in search-index-compiler so we can sort on them
