### ISSUE TITLE
Adding ESLint

### ISSUE THREAD

**Issue by GuilleAngulo** [colbyfayock/next-wordpress-starter#159]
> This error made me think if could be a good idea adding eslint to the project (and to github actions workflow) in adittion to prettier. The project could take advantage of having this check at pre-commit identifying this kind of errors that don't break the flow, unused variables, etc resulting in a more consistent code. What do you think? If you like the idea I can prepare an initial configuration.

_Referring to the code review #158_

**Comment by colbyfayock** [comment]
interesting. thinking back, i actually just assumed prettier would catch this but i guess it really doesnt do much more than formatting

im down for that. i actually prefer configuring via ESLint but didn't want to spend a ton of time on it originally

there should be plugins available that will make prettier use the eslint config. regardless of how it's set up, both eslint and prettier should source from the same config to make sure there's not conflicts between the 2 and generally easier to manage

i vote eslint as the source of truth but im open to ideas

**Comment by GuilleAngulo** [comment]
Exactly, in my opinion having both working together is the best scenario: prettier for visual formatting and ESlint for javascript rules and patterns checks.

This [plugin](https://github.com/prettier/eslint-plugin-prettier#readme) makes it possible for the two to work together without conflicts: it runs prettier as an ESlint rule.

**Comment by colbyfayock** [comment]
cool, did you want to take it up?

**Comment by colbyfayock** [comment]
here's another way ive done it in the past https://github.com/colbyfayock/gatsby-starter-leaflet/blob/master/package.json#L64

**Comment by GuilleAngulo** [comment]
Sure. If you like the idea, I can open a PR with an initial configuration and we can make the changes you think make more sense inside. What do you think?

**Comment by colbyfayock** [comment]
yeah that sounds great :)
