### ISSUE TITLE
Vercel Zlib Not Found

### ISSUE THREAD

**Issue by jahzlariosa** [colbyfayock/next-wordpress-starter#166]
Any idea why I get this when deploying this template to Vercel?

`

09:21:08 | > Build error occurred
-- | --
09:21:08 | Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /vercel/path0/node_modules/canvas/build/Release/libpng16.so.16)
09:21:08 | at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
09:21:08 | at Module.load (internal/modules/cjs/loader.js:928:32)
09:21:08 | at Function.Module._load (internal/modules/cjs/loader.js:769:14)
09:21:08 | at Module.require (internal/modules/cjs/loader.js:952:19)
09:21:08 | at require (internal/modules/cjs/helpers.js:88:18)
09:21:08 | at Object.<anonymous> (/vercel/path0/node_modules/canvas/lib/bindings.js:3:18)
09:21:08 | at Module._compile (internal/modules/cjs/loader.js:1063:30)
09:21:08 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
09:21:08 | at Module.load (internal/modules/cjs/loader.js:928:32)
09:21:08 | at Function.Module._load (internal/modules/cjs/loader.js:769:14)
09:21:08 | at Module.require (internal/modules/cjs/loader.js:952:19)
09:21:08 | at require (internal/modules/cjs/helpers.js:88:18)
09:21:08 | at Object.<anonymous> (/vercel/path0/node_modules/canvas/lib/canvas.js:9:18)
09:21:08 | at Module._compile (internal/modules/cjs/loader.js:1063:30)
09:21:08 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
09:21:08 | at Module.load (internal/modules/cjs/loader.js:928:32)
09:21:08 | error Command failed with exit code 1.

`

Thanks

**Comment by DLevai94** [comment]
@jahzlariosa did you solved this?
