### ISSUE TITLE
Use WordPress Setting for Posts per Page

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#171]
We can query for the configured posts per page set in the Reading tab in the admin via:
```
query MyQuery {
  allSettings {
    readingSettingsPostsPerPage
  }
}
```

![image](https://user-images.githubusercontent.com/1045274/119271096-0961e600-bbce-11eb-99c4-02e1bdfa031c.png)

**Comment by GuilleAngulo** [comment]
hey! i was just taking look at this one. Do you think still makes sense to allow the user use `POST_PER_PAGE` variable at `next.config.js` overwritting this value? Probably the recommended is to query this value as single source of truth ... what do you think @colbyfayock?

**Comment by colbyfayock** [comment]
yeah i think i agree with you, probably makes sense with WP being the single source of truth, especially because it's opt-in. we could always throw a warning if someone is currently using it after making this change and keep it in for a little bit
