### ISSUE TITLE
Contents and posts are not updating

### ISSUE THREAD

**Issue by tareq0065** [colbyfayock/next-wordpress-starter#208]
After building and deployed to the vercel the contents and posts are not updating when I am creating new posts on WordPress. Do I need to build and deploy every time I create a new post?

**Comment by colbyfayock** [comment]
hey @tareq0065 when using WordPress headlessly (and any other headless CMS) you need to make your hosting provider (Vercel) aware of the changes that you made, as there isn't any relationship between the 2 by default

you can use web hooks to do this by creating a Deploy Hook in Vercel:

https://vercel.com/docs/more/deploy-hooks

Then installing WP Webhooks: 

https://wordpress.org/plugins/wp-webhooks/

To automatically trigger that hook on content update

**Comment by tareq0065** [comment]
@colbyfayock Hey this is awesome. Thanks for your reply ........

**Comment by colbyfayock** [comment]
here's a tutorial that uses Netlify in case it helps https://spacejelly.dev/posts/how-to-automate-deployments-on-content-change-in-wordpress-with-wp-webhooks-and-netlify/
