### ISSUE TITLE
Apollo error for Absolute URLs

### ISSUE THREAD

**Issue by CodMoncai** [colbyfayock/next-wordpress-starter#215]
When I use your Repo and then add in my own Wordpress URL, I get an Apollo error for Absolute URLs, your repo has no one commenting on this, how can I fix this? I also get the same error when I put your own URL in

**Comment by GuilleAngulo** [comment]
hey @CodMoncai could you please provide more details on the error? Sometimes absolute url errors on Apollo have to do with the url construction: `http://`wordpressite.com/graphql or `http://`localhost:[port]/graphql

**Comment by colbyfayock** [comment]
hey @CodMoncai any luck on this?
