### ISSUE TITLE
HPE_INVALID_HEADER_TOKEN

### ISSUE THREAD

**Issue by ActivatedDigital** [colbyfayock/next-wordpress-starter#217]
Hello, since the update of wordpress 5.8 it does not work anymore 
we receive an error : HPE_INVALID_HEADER_TOKEN
"reason: Parse Error: Invalid header value char "
do you have an idea where it comes from?

**Comment by colbyfayock** [comment]
hey @ActivatedDigital i just upgraded my own wordpress instance to 5.8 and i'm not able to reproduce the issue, can you provide more information or ideally a codesandbox where you're able to reproduce this?
