### ISSUE TITLE
Upgrade Husky to most recent version

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#240]
We're currently anchored on husky@4.3.8 due to the difference in the API

We need to upgrade to the most recent version and update the precommit scripts to follow the new method

Tutorial to help out: https://spacejelly.dev/posts/how-to-automate-code-linting-in-next-js-with-eslint-husky-git-hooks/#step-3-automatically-linting-during-development

**Comment by IvanSanchezSalvador** [comment]
Can i work on this task?

**Comment by colbyfayock** [comment]
all yours!
