### ISSUE TITLE
Export Sass colors to use in the UI

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#247]
Is there a way for us to export Sass colors to use within JavaScript?

This article may prove to be helpful: https://css-tricks.com/getting-javascript-to-talk-to-css-and-sass/

This will help keep consistency throughout the application

Can start by using this with the Next.js Progress Bar

**Comment by PhattOZ** [comment]
Hi! Would you mind if I try implementing this issue?

**Comment by colbyfayock** [comment]
Yup sure @PhattOZ all yours

**Comment by PhattOZ** [comment]
I'm having a trouble setting up the development environment. I there any descriptive guide about setting up wordpress and graphql with this template I could go and look at? Thanks

**Comment by colbyfayock** [comment]
yup! i have it here: https://next-wordpress-starter.spacejelly.dev/posts/how-to-create-a-headless-wordpress-blog-with-next-js-wordpress-starter/

though in that example we use Create Next App, so if you're contributing, you want to skip that and fork it instead

basically you'll need:
* WordPress
* Add WPGraphQL plugin in WordPress
* Add the environment variable:
```
WORDPRESS_GRAPHQL_ENDPOINT="https://yourwordpresssite.com/graphql"
```

The README also has some instructions as well:

https://github.com/colbyfayock/next-wordpress-starter#-getting-started

let me know if there's something particular that's not clear

otherwise I can provide a wordpress link that you can use to develop with :)
