### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#27]
We should provide an automatically generated sitemap.xml  file

Can we  take advantage of the work we did with the search index?

Is there a plugin we can roll this into dynamically?

**Comment by lelouchB** [comment]
Hey 
Is this something that we can use 
https://wordpress.org/plugins/google-sitemap-generator/

First time with WordPress 😁

**Comment by colbyfayock** [comment]
thats a good question @lelouchB we would have to see if the sitemap structure is queryable from GraphQL

that said, i'm somewhat trying to avoid plugins. if you look at the files in plugins, im currently building an index of the site using the content information and manually building it, i would think we could do something similar with the sitemap 🤔

**Comment by lelouchB** [comment]
Yeah sure
I understand 
I will start exploring the project and then try to pick up an issue 

Thanks

**Comment by doingandlearning** [comment]
Yeah - I think we probably want to do the indexing on the Next side, not least of all because we may add some 'non-WP' pages in the build

**Comment by GuilleAngulo** [comment]
If is available, would like to give a try :point_up:

**Comment by colbyfayock** [comment]
all you @GuilleAngulo was thinking this would fit in nicely with the plugin system!
