### ISSUE TITLE
Failed to load next.config.js

### ISSUE THREAD

**Issue by nickcanarelli** [colbyfayock/next-wordpress-starter#274]
After cloning the repository I created and set my `.env.local` file, ran `npm i` then ran `npm run dev`. The server starts, env is loaded from `.env.local` however it immediately fails prompting me with the following:

```
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Not supported
    at Object.loadConfig [as default] (C:\Users\Nick\Desktop\rebuild\node_modules\next\dist\server\config.js:399:74)
    at async NextServer.loadConfig (C:\Users\Nick\Desktop\rebuild\node_modules\next\dist\server\next.js:110:22)
    at async NextServer.prepare (C:\Users\Nick\Desktop\rebuild\node_modules\next\dist\server\next.js:92:24)
    at async C:\Users\Nick\Desktop\rebuild\node_modules\next\dist\cli\next-dev.js:126:9
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rebuild@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rebuild@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nick\AppData\Roaming\npm-cache\_logs\2021-10-29T19_47_30_427Z-debug.log
```

**Comment by colbyfayock** [comment]
hey @nickcanarelli what version of node are you using? `node -v`

**Comment by nickcanarelli** [comment]
> hey @nickcanarelli what version of node are you using? `node -v`

Hey @colbyfayock I ended up uninstalling node and downgrading to v14.0.0. Seems like that was the issue and we're up and running. Thanks for checking in!

**Comment by colbyfayock** [comment]
ah gotcha, glad to hear you got it working!

**Comment by colbyfayock** [comment]
Next.js requires 12.22.0

https://nextjs.org/docs/getting-started#system-requirements

**Comment by abbasahmad** [comment]
Always the same issue: 
![image](https://user-images.githubusercontent.com/8807863/160906049-92caa207-1677-4bde-8eb7-cb5c7deb0702.png)

**Comment by colbyfayock** [comment]
@abbasahmad is this related to this Starter? your error is stating that it's missing a specific commerce module that isn't related to this project

**Comment by abbasahmad** [comment]
Indeed. i got confused with all the different gitHub issues i had opened.

my apologies!
