### ISSUE TITLE
Wordpress Backend Update post, But Frontend Apollo Cache Remain Old Version

### ISSUE THREAD

**Issue by idpelago** [colbyfayock/next-wordpress-starter#297]
when we updated a post in the wordpress admin panel, the changes are not showing up in the frontend site.
I think the issue come from apollo client's cache.

is there any ways to counter this issue, so we can immediately see the changes when we hit the update button on the wordpress admin?

Best regards

**Comment by colbyfayock** [comment]
that looks like a similar issue to https://github.com/colbyfayock/next-wordpress-starter/issues/286

the last comment there has what their solution was, maybe give that a try?

**Comment by idpelago** [comment]
Hi @colbyfayock, thanks for your reply!

Sure, I will give it a try :)
