### ISSUE TITLE
Timing out

### ISSUE THREAD

**Issue by skinnard** [colbyfayock/next-wordpress-starter#299]
Hey there, thanks for building this, super excited about trying this out. 

The problem is, running the dev server it just hangs and never loads, and running a build just times out. Have you seen this before? 

Here is the error when I run `yarn build`

Node: v14.16.1

```
...

warn  - Restarted static page generation for /posts/quia-corporis-nisi-quam-et-provident because it took more than 60 seconds
warn  - Restarted static page generation for /posts/hello-world because it took more than 60 seconds
warn  - Restarted static page generation for /posts/page/1 because it took more than 60 seconds
warn  - Restarted static page generation for /posts/page/2 because it took more than 60 seconds
> Build error occurred
Error: Static page generation for /404 is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
    at onRestart (/Users/glen/Sites/personal/my-blog/node_modules/next/dist/build/index.js:487:31)
    at Worker.exportPage (/Users/glen/Sites/personal/my-blog/node_modules/next/dist/lib/worker.js:49:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/glen/Sites/personal/my-blog/node_modules/next/dist/export/index.js:412:32
    at async Span.traceAsyncFn (/Users/glen/Sites/personal/my-blog/node_modules/next/dist/trace/trace.js:74:20)
    at async Promise.all (index 0)
    at async /Users/glen/Sites/personal/my-blog/node_modules/next/dist/export/index.js:407:9
    at async Span.traceAsyncFn (/Users/glen/Sites/personal/my-blog/node_modules/next/dist/trace/trace.js:74:20)
    at async /Users/glen/Sites/personal/my-blog/node_modules/next/dist/build/index.js:987:17
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by colbyfayock** [comment]
hey i haven't ran into this before, the only time ive seen issues is if the API that i'm requesting data from is hanging, but page creation shouldn't take taht long if you're not experiencing something similar with other nextjs apps

**Comment by kevinctofel** [comment]
@colbyfayock I’m actually seeing the same thing on a local dev instance. FWIW, my site has nearly 900 posts. But it’s timing out after creating the first few .xml files; no posts or pages are created. Just hangs. Could be a different issue but wanted to mention. Cheers!

**Comment by colbyfayock** [comment]
thanks for the heads up, ill see if i can repro. i need to find a bigger wordpress to test with!

**Comment by skinnard** [comment]
@colbyfayock For the record I was never able to use the repo, everything just keep timing out and it was a fresh install with zero posts or data. Anyway thanks for looking into it, cheers!

**Comment by colbyfayock** [comment]
@skinnard want to try using the demo site GraphQL endpoint to see if you still have issues with that? https://nextwpprod.wpengine.com/graphql

**Comment by glenhodges** [comment]
@colbyfayock ya good call, Ill do that, cheers and thanks again.

**Comment by colbyfayock** [comment]
closing this issue, let me konw if you're still seeing issues and are able to identify any info about what may be causing
