### ISSUE TITLE
Maintenance mode  (feature request)

### ISSUE THREAD

**Issue by zr87** [colbyfayock/next-wordpress-starter#300]
Hi!.
At some point, maintenance mode is a must-have anyway.
I'd like to kickstart a brainstorm on the topic of how this functionality could be implemented.

My first idea is:
1. add a WordPress plugin that adds a custom settings field for maintenance mode, as boolean.
2.  next app should query this custom settings field from WP (what would be the most efficient way to the query?)
3. if the setting is true then show a pre-rendered custom maintenance page

Constructive ideas are appreciated!

**Comment by zr87** [comment]
A concrete solution found in[ this article](https://www.jondjones.com/frontend/jamstack/configuring-error-pages-and-maintenance-pages-with-netlify-and-nextjs/)

**Comment by colbyfayock** [comment]
hey @zr87 i wonder if it's worth pinging https://github.com/wp-graphql/wp-graphql to see if it's something queryable or that could be added
