### ISSUE TITLE
Gives out err 'Error: EPERM: operation not permitted.'

### ISSUE THREAD

**Issue by touseefcodes** [colbyfayock/next-wordpress-starter#304]
```event - compiled client and server successfully in 3.7s (739 modules)
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, open 'D:\colby-headless-next\.next\trace'
Emitted 'error' event on WriteStream instance at:
    at D:\colby-headless-next\node_modules\next\dist\compiled\@vercel\nft\index.js:1:287421
    at D:\colby-headless-next\node_modules\next\dist\compiled\@vercel\nft\index.js:1:287860
    at FSReqCallback.oncomplete (fs.js:180:23) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'D:\\colby-headless-next\\.next\\trace'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-wordpress-starter@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the next-wordpress-starter@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I am using Local by Flywheel for my Wordpress.  Can anyone guide me why this happens?

**Comment by colbyfayock** [comment]
hey! thtas a strange one, but i dont think that has anything to do with the starter itself rather it looks like possibly a permissions issue for something Next.js is doing

have you been able to spin up other Next.js projects similarly?

**Comment by touseefcodes** [comment]
i used `http://mysite.local/graphql` in the `.env.local` now, the page is not showing, although it is loading infinitely.

**Comment by alexandruvisan19** [comment]
also have a similar issue with it, same error

**Comment by colbyfayock** [comment]
Do either of you see any activity in the terminal as it's loading? Such as compilation messages?

**Comment by alexandruvisan19** [comment]
![image](https://user-images.githubusercontent.com/79447321/147365323-5eee03c6-5f24-497b-bbee-eb7d5334f1e9.png)

**Comment by touseefcodes** [comment]
![err colby-theme](https://user-images.githubusercontent.com/81577619/147832182-ae9b450d-526a-4360-b356-0492c8836b3a.png)

This is what Im gettinng... It stops there and I have to wait years for that.

**Comment by colbyfayock** [comment]
@touseefcodes did you confirm @alexandruvisan19's fix is working for you now too?

**Comment by touseefcodes** [comment]
@colbyfayock yes captain
