### ISSUE TITLE
Add typescript support

### ISSUE THREAD

**Issue by AbdeladimSaouiss** [colbyfayock/next-wordpress-starter#306]
This project doesn't support typescript for the moment.

It would be great if typescript was added, since most of JavaScript project nowadays are built with typescript.

Can I take over it ?

**Comment by colbyfayock** [comment]
hey @AbdeladimSaouiss i dont think that statement is true that most projects are typescript, but if you'd like to create a PR that introduces support, that sounds good. I'm however not looking to transform the entirety of the project to typescript so it would be minimal support

that said feel free to fork and make your own version with full typescript support!

**Comment by AbdeladimSaouiss** [comment]
@colbyfayock Noted, thank you
