### ISSUE TITLE
Error: A required parameter (slugParent) was not provided as a string in getStaticPaths for /[slugParent]/[[...slugChild]]

### ISSUE THREAD

**Issue by urandombg** [colbyfayock/next-wordpress-starter#322]
Hey, Folks!
I just clonned this starter project and tried to build it under windows, but compiler output these errors:

"C:\Program Files\nodejs\node.exe" C:\Users\urandom\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js run wpe-build
yarn run v1.22.10
$ npm run build

> next-wordpress-starter@0.1.0 build
> next build

info  - Loaded env from D:\Sites\2022\next-wordpress-starter\.env.local
info  - Checking validity of types
postcss-resolve-url: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
Successfully created: wp-search.json
Successfully created: feed.xml
Successfully created: sitemap.xml
Successfully created: [slug].png
info  - Creating an optimized production build
info  - Compiled successfully

> Build error occurred
Error: A required parameter (slugParent) was not provided as a string in getStaticPaths for /[slugParent]/[[...slugChild]]
    at D:\Sites\2022\next-wordpress-starter\node_modules\next\dist\build\utils.js:558:27
    at Array.forEach (<anonymous>)
    at D:\Sites\2022\next-wordpress-starter\node_modules\next\dist\build\utils.js:551:29
    at Array.forEach (<anonymous>)
    at buildStaticPaths (D:\Sites\2022\next-wordpress-starter\node_modules\next\dist\build\utils.js:518:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async D:\Sites\2022\next-wordpress-starter\node_modules\next\dist\build\utils.js:641:119
    at async Span.traceAsyncFn (D:\Sites\2022\next-wordpress-starter\node_modules\next\dist\trace\trace.js:74:20) {
  type: 'Error'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
There is no password protected route to GraphQL or any other limitations.

Please, advise how to fix it.

**Comment by colbyfayock** [comment]
hey @urandombg is your wordpress instance public that I could try testing with it?

otherwise try adding this console.log statement before the return statement inside of `getStaticPaths` and see if it shows any results in your terminal

```
console.log(paths.filter(({ params }) => !params.slugParent))
```

if not results it'll log `[]`

**Comment by urandombg** [comment]
Hi @colbyfayock , thanks for your replay!

The URL is [https://www.dentaconbg.com/apix/graphql](url)

**Comment by colbyfayock** [comment]
start debugging this and notice that the page that's causing an issue is:
```
  {
    __typename: 'Page',
    children: [],
    featuredImage: null,
    id: 'cG9zdDoxODUzOQ==',
    menuOrder: null,
    parent: null,
    slug: 'nachalo',
    title: 'Начало',
    uri: '/'
  },
```

Notice the URI is `/` where all of the pages that get processed inside of `/src/pages/[slugParent]/[[...slugChild]].js` 

it's not used to seeing the root i guess

did you manually set that? are you using any configuration that might have changed that?

we should be able to handle that as an issue but im curious what the fix woudl look like based on that information and the use case

**Comment by urandombg** [comment]
Thanks @colbyfayock for your investigation! Yes, page is set from wordpress reading settings to be static, not to show latest posts.

**Comment by colbyfayock** [comment]
awesome (that we found the issue haha), ill see if that's something im able to handle programmatically though im not totally sure on that one, if nothing else I can prevent it from failing and log a warning that it wont work

thanks for letting me know

**Comment by colbyfayock** [comment]
ohhh thats interesting, any interest in putting together a PR to see how that would look? @palespectre

**Comment by pierrec-dahive** [comment]
Sure @colbyfayock, I'll give it a shot

**Comment by palespectre** [comment]
Sure @colbyfayock, I'll give it a shot

**Comment by eliawk** [comment]
@palespectre It wouldn't be possible to just filter the page set as a static home page with the '/' uri from the graphql query?
in this case you shouldn't need to modify anything in the [[...slugChild]] file
