### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#34]
I'd really like to work on providing a great reading experience with this Starter by default

I'm not sure if there are any good drop-ins or if we want to manually work through the typography, but it definitely needs work, as it's kind of just droppped in right now

open to ideas to discuss this, but the solution should be CSS based

**Comment by colbyfayock** [comment]
Some options so far, open to more:
* https://github.com/tailwindlabs/tailwindcss-typography
* https://github.com/kognise/water.css [npm link](https://www.npmjs.com/package/water.css)

**Comment by HeinSnyman** [comment]
I think water.css looks good as well as some of the other frameworks mentioned in the css tricks blog post. I also found this one https://milligram.io/#typography which I think also looks good. I will implement some of these and get back here with screenshots.

**Comment by colbyfayock** [comment]
that sounds awesome thanks @HeinSnyman - i thought the MVP one looked nice too

either way, while im open to anything, i really like the idea of using a solution that doesn't require classes and such, just cause it makes it easier to drop in and people dont have to think about it as much, but we'll see :)

excited to see what you come up with!

**Comment by HeinSnyman** [comment]
I gave the following frameworks a try that I thought would look good. I kept in mind to use the ones that doesn't require classes to be added to the code.

## Axist.css
### Home Page
<img width="1680" alt="axist_home-page" src="https://user-images.githubusercontent.com/22816814/96879213-0b1ecc00-147c-11eb-9221-915322064094.png">

### Post Page
![axist_post](https://user-images.githubusercontent.com/22816814/96879432-546f1b80-147c-11eb-94f7-14c4d32644fe.png)

## Comet.css
### Home Page
<img width="1680" alt="comet_home-page" src="https://user-images.githubusercontent.com/22816814/96880264-47066100-147d-11eb-835c-7ed49ea21824.png">

### Post Page
![comet_post](https://user-images.githubusercontent.com/22816814/96880370-630a0280-147d-11eb-842d-f5451b716782.png)


## Milligram.css

### Home Page
<img width="1679" alt="milligram_home" src="https://user-images.githubusercontent.com/22816814/96880690-c005b880-147d-11eb-9229-d029657a3928.png">

### Post Page
![milligram_blog-post](https://user-images.githubusercontent.com/22816814/96880742-d4e24c00-147d-11eb-9dd7-778c7c1f949f.png)


## Mvp.css
### Home Page
<img width="1679" alt="mvp_home-page" src="https://user-images.githubusercontent.com/22816814/96880875-f9d6bf00-147d-11eb-9886-0150a03f2de4.png">

### Post Page
![mvp_post](https://user-images.githubusercontent.com/22816814/96880948-0bb86200-147e-11eb-9f5f-98f1340b96cc.png)


## Water.css
### Home Page
<img width="1680" alt="water_home-page" src="https://user-images.githubusercontent.com/22816814/96881053-27236d00-147e-11eb-8494-7f5d08f52040.png">

### Post Page
![water_post](https://user-images.githubusercontent.com/22816814/96881110-399da680-147e-11eb-8eb8-7108a349c872.png)

## Some of the above frameworks alters the layout whereas the below frameworks only alters the typography

## Medium.css
### Home Page
<img width="1680" alt="medium_home" src="https://user-images.githubusercontent.com/22816814/96881378-7ff30580-147e-11eb-9118-dc08f73abbdf.png">

### Post Page 
![medium_blog-post](https://user-images.githubusercontent.com/22816814/96881481-9b5e1080-147e-11eb-92e6-9d146cfd3605.png)

## Typebase.css
### Home Page
<img width="1680" alt="typebase_home" src="https://user-images.githubusercontent.com/22816814/96881543-ac0e8680-147e-11eb-97b7-27e2ee2b5e9c.png">

### Post Page
![typebase_blog-post](https://user-images.githubusercontent.com/22816814/96881589-b892df00-147e-11eb-8844-619660f863fc.png)

---
Wouldnt it be better to use a framework that only works on the typography for this? Or do we just work around that? 

I found more of these drop in frameworks here: https://dohliam.github.io/dropin-minimal-css/

Let me know which one you think would work the best and I will make a PR.

Sorry for the crazy long post.😅

**Comment by colbyfayock** [comment]
thanks for all of this 🙏 im kind of under the same impression that a typography only one would be nice so we're not making too many UI assumptions

interestingly though i like what Water.css does the best out of those, but if we pick 1 typography framework, we could work in some of the ncie things that Water has like the blockquote style

im gonna poke around that drop-in website before i answer, thats pretty cool

**Comment by colbyfayock** [comment]
the nice thing about the style.css one is it's available on npm so we can import that right into the project in global i would think 🤔

**Comment by HeinSnyman** [comment]
I like Style.css as well! It also doesn't change the layout of the project too drastically.  Maybe it's the one to go with.

## Home page 
<img width="1679" alt="style_home-page" src="https://user-images.githubusercontent.com/22816814/96978198-643f3c00-151e-11eb-85b4-857c13c5d69d.png">

## Post Page 
![style_blog-post](https://user-images.githubusercontent.com/22816814/96978224-6c977700-151e-11eb-8a61-0782565c4cc8.png)

**Comment by colbyfayock** [comment]
cool lets go with that :) the nice thing about including this inside of global.scss is that it will go into the next.js pipeline and it will also allow someone to easily remove it should they not like it!
