### ISSUE TITLE
Error when a category is selected in only 1 post (no other post shares the same category)

### ISSUE THREAD

**Issue by vincent-roye** [colbyfayock/next-wordpress-starter#341]
Server Error
TypeError: Cannot read properties of undefined (reading 'posts')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
src\lib\posts.js (330:28) @ getRelatedPosts

  328 |   }
  329 | 
> 330 |   if (Array.isArray(related.posts) && related.posts.length > count) {
      |                            ^
  331 |     return related.posts.slice(0, count);
  332 |   }
  333 |

**Comment by colbyfayock** [comment]
@vincent-roye is your wordpress instance GraphQL endpoint publicly available to use for debugging?

i'm not immediately seeing how the code could get that error given related should exist at the top of that block

**Comment by vincent-roye** [comment]
@colbyfayock no it isn't but I solve the issue by modifying:

**src\lib\posts.js:

Line 330:**

  if (Array.isArray(related.posts) && related.posts.length > count) {
    return related.posts.slice(0, count);
  if (related) {
    if (Array.isArray(related.posts) && related.posts.length > count) {
      return related.posts.slice(0, count);
    }
  }
  
and **\src\pages\posts\[slug].js

Line 151:**

  const { category: relatedCategory, posts: relatedPosts } = await getRelatedPosts(categories, postId);
  const hasRelated = relatedCategory && Array.isArray(relatedPosts) && relatedPosts.length;
  const related = !hasRelated
    ? null
    : {
        posts: relatedPosts,
        title: {
          name: relatedCategory.name || null,
          link: categoryPathBySlug(relatedCategory.slug),
        },
      };

  const getRelatedPostsRes = await getRelatedPosts(categories, postId);

  let related = null;

  if (getRelatedPostsRes) {
    const { category: relatedCategory, posts: relatedPosts } = getRelatedPostsRes;
    const hasRelated = relatedCategory && Array.isArray(relatedPosts) && relatedPosts.length;
    related = !hasRelated
      ? null
      : {
          posts: relatedPosts,
          title: {
            name: relatedCategory.name || null,
            link: categoryPathBySlug(relatedCategory.slug),
          },
        };
  }
