### ISSUE TITLE
Author URL should be based on Name

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#35]
Currently because of the way that we have to query user data via GraphQL, we're using the slug for the author pages

We can instead parameterize the author's full name providing a friendlier URL

https://github.com/fyalavuz/node-parameterize

Doing this consistently, then using that value to look up the parameterized versions of the author's name in the all users query which we're already making can help us look that user up to grab their details

**Comment by GuilleAngulo** [comment]
Would like to give a try :raising_hand:

**Comment by colbyfayock** [comment]
sure thing! let me know if you have any questions about it

**Comment by GuilleAngulo** [comment]
Ok, here is what I though (Also to clear the structure in my head 😆). Please let me know if something is wrong or missing, or exists a better approach:

At _Metadata_:

- Change **Author Link** href to be **/authors/${parameterize(name)**. (Is this the only link to the author's page?

At _authors/[slug]_ page:

- **getStaticProps**. Get the user by checking the new received url param with the array of users (using parameterize(names) while iterating search). Once having the author, retrieving post by its slug is the same.
- **getStaticPaths**. Use parameterize(name) of all authors as the param to create the paths.

**Comment by colbyfayock** [comment]
Author Link: Yeah, I believe that's the only spot. we will probably want to update `authorPathBySlug` to a new function that represents what we're doing with the`parameterize` inside it . `authorPathByName` maybe? and then you can use that function to build the path everywhere

The rest i think sounds right!

**Comment by GuilleAngulo** [comment]
Yes! Made that way, adding two new functions to users lib file. And I kept authorPathBySlug and getUserBySlug in case they are needed in future.
