### ISSUE TITLE
Get 404 on pages

### ISSUE THREAD

**Issue by eliawk** [colbyfayock/next-wordpress-starter#354]
Hello, 
everything work fine but if I visit any pages I get a 404.
Posts, categories,... everything else is working correctly.

![Schermata 2022-04-20 alle 18 27 56](https://user-images.githubusercontent.com/362016/164278486-fe7b5f0e-0212-4cf8-a719-486418bcbb62.png)

**Comment by eliawk** [comment]
@colbyfayock I've fixed removing the baseurl form the uri:
```
  const paths = pages
    .filter(({ uri }) => typeof uri === 'string')
    .map(({ uri }) => {
      const segments = uri
        .replace('http://localhost:3000', '')
        .split('/')
        .filter((seg) => seg !== '' && seg !== undefined);
      return {
        params: {
          slugParent: segments.shift(),
          slugChild: segments,
        },
      };
    });
```
how did you make this working without this fix?

**Comment by colbyfayock** [comment]
hey i'm not really sure about this one? could it be a custom setting you have for permalinks or how URLs are returned? haven't seen this issue before

**Comment by eliawk** [comment]
@colbyfayock yes it was my fault. I've had this:
```
function custom_frontend_url($permalink, $post)
{
  $custom_permalink = str_replace(home_url(), HEADLESS_URL,  $permalink);
  return $custom_permalink;
};

add_filter('page_link', 'custom_frontend_url', 10, 2);
add_filter('post_link', 'custom_frontend_url', 10, 2);
// If you use custom post types also add this filter.
add_filter('post_type_link', 'custom_frontend_url', 10, 2);
```
in order to change the links from the WP be, but this affects also the uri in the grapqhl queries.

**Comment by colbyfayock** [comment]
ah thanks for sharing, glad you were able to figure it out! is this something that can be avoided in the starter? i tend to think that's a custom feature that wouldn't make sense in the starter beyond this issue that people can search for. thoughts?
