### ISSUE TITLE
Documentation for modifying data nodes and UI

### ISSUE THREAD

**Issue by huynhtan1808** [colbyfayock/next-wordpress-starter#358]
Hi, I really want to display the post's Featured Image in Post Card. Does anyone have any idea? 

Thank you.

**Comment by colbyfayock** [comment]
hey @huynhtan1808 

you can copy this component into the post cards: https://github.com/colbyfayock/next-wordpress-starter/blob/main/src/pages/posts/%5Bslug%5D.js#L77

then you need to make the data available for each instance of the card

for the homepage you can do that by updating:

https://github.com/colbyfayock/next-wordpress-starter/blob/main/src/pages/index.js#L63

to be:
```
  const { posts, pagination } = await getPaginatedPosts({
    queryIncludes: 'all',
  });
```

Or you can update the `archive` query to include the featured image data node:

https://github.com/colbyfayock/next-wordpress-starter/blob/main/src/data/posts.js#L38

**Comment by huynhtan1808** [comment]
Work like a champ, thank you so much
