### ISSUE TITLE
No CSS render on any live page

### ISSUE THREAD

**Issue by MichaelSpect** [colbyfayock/next-wordpress-starter#364]
Hello
I have used this starter to build a site.
After deploying it on Netlify live site doesn't render css. Looks like it's without any style.
https://merry-fenglisu-d1b5fa.netlify.app/

After that, I have test new clone of next-wordpress-starter (and just change WORDPRESS_GRAPHQL_ENDPOINT) and the results is the same after deployment. No CSS render on any live page!
https://silver-speculoos-e5340f.netlify.app/

Any idea?

Thanks

**Comment by colbyfayock** [comment]
that's a strange one, do you have the Essential Next.js Plugin installed?

**Comment by MichaelSpect** [comment]
Hello Colby,

I continue to investigate the matter.
Yes, I had Essential Next.js Plugin installed.
The same repo I deployed on Vercel and works well.
https://dumident-next-js-wp.vercel.app/

This was a standard Next JS build.

After that, I tried Next static export (with "out" production folder) on
Netlify, but I had to uninstal Essential Next.js Plugin.
In this scenario Next-Wordpress-Starter works as it should be, but mine
Dumident site has problems with production on Netlify because of using Next
Images.
Now, I'll try to refactor these Next Images and try static deployment
again.

My conclusion is that there is some problem with standard Next production
and Netlify.
My Netlify deploy settings was default (build: next build, folder: .next,
Essential Next.js Plugin installed).

**Comment by colbyfayock** [comment]
if you run `yarn build` or generally `next build` in the project locally do you get any errors or anything weird looking?

**Comment by MichaelSpect** [comment]
Locally built runs well and everything looks good.

I stopped to investigate the problem with the Netlify build. I set it up to
work well with export and all static pages.
https://merry-fenglisu-d1b5fa.netlify.app/

Thanks for the support and starter project. I like it a lot. :)

**Comment by colbyfayock** [comment]
awesome, glad to hear that, gonna close this, but if you figured out what the issue was I'd still be curious to hear what it is!
