### ISSUE TITLE
Feature: Support for On Demand Revalidation

### ISSUE THREAD

**Issue by defser** [colbyfayock/next-wordpress-starter#379]
Adding  support for On Demand Revalidation

https://ramonmetzker.dev/nextjs-on-demand-revalidation-with-wordpress

It is possible to revalidate a post on demand, someone willing to work on this?

**Comment by colbyfayock** [comment]
is this something that would cause any issues for people not using it?

**Comment by colbyfayock** [comment]
closing this as it's something anyone can add to their page configuration by simply defining it in `getStaticProps` 

tutorial: https://www.youtube.com/watch?v=_isECpf3-8s
