### ISSUE TITLE
Use Blocks instead of Rendered Content

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#4]
The post content is currently using standard rendered content and using `dangerouslySetInnerHTML` to set that HTML content. We would ideally use Blocks to take full advantage of the Gutenberg editor when building content.

**Comment by colbyfayock** [comment]
We should probably wait to do this until the GraphQL Issue is resolved

https://github.com/colbyfayock/next-wordpress-starter/issues/5

**Comment by doingandlearning** [comment]
I'm happy to look at this :)

**Comment by doingandlearning** [comment]
https://github.com/pristas-peter/wp-graphql-gutenberg - this plugin exposes the block content to graphql

**Comment by colbyfayock** [comment]
sounds like we should move forward with that then 🤷

**Comment by doingandlearning** [comment]
I think that the only way to do this - seperate content from markup - is to use ACF (advanced custom fields) on the backend and query for the firleds that are used.

I'd also recommend not allowing any Gutenberg blocks in the first instance.

This issue now is a documentation issue and maybe there is a version which just uses dangerouslySetInnerHTML?

**Comment by colbyfayock** [comment]
do you think we want to or do you think it would make sense to still use blocks using the rendered HTML? my only thinking is maybe there could be instance where we would want to provide custom components for blocks making it more flexible. so the change here would essentially be still moving to blocks, but using `dangerouslySetInnerHTML` with the blocks

thoughts?

**Comment by colbyfayock** [comment]
@doingandlearning what do you think about the above?

**Comment by colbyfayock** [comment]
Talked to Jason Bahl about this, on his website they parse the html to create components. we can probably do this safely and not impact performance since it would be at build time

https://github.com/wp-graphql/wpgraphql.com/blob/master/src/templates/WpCodeSnippet.js#L56

**Comment by doingandlearning** [comment]
Yeah - I think that's probably fine. I *also* talked to Jason about this and was surprised that blocks aren't being registered in the database, so this makes the query much slower. 

I think for now, it's good to parse the html :)
