### ISSUE TITLE
Minor bug rendering Site Title when containing HTML entities

### ISSUE THREAD

**Issue by GuilleAngulo** [colbyfayock/next-wordpress-starter#40]
### Description

If the WordPress Site Title contains any entity character, like **apostrophe** or **&**, it haves problems of "double" codification at **Nav component** and at **title tag**.

### Screenshots

|Bug                    |
| ---------------------------------- |
| ![apostrophe-encode](https://user-images.githubusercontent.com/50624358/95905621-7a573a80-0d6f-11eb-8173-2656653a77ac.png)|

**Comment by colbyfayock** [comment]
ah great catch @GuilleAngulo i'll try to get a fix in
