### ISSUE TITLE
Image caption not centrally aligned, image is squished when resizing

### ISSUE THREAD

**Issue by vikiyev** [colbyfayock/next-wordpress-starter#405]
Currently out of the box, image captions are not aligned with the image. This was mentioned in #203 , but I'm not sure if this was fixed or was left. Also, when resizing the page, images loses its aspect ratio, as seen in the 2nd screenshot

![Screenshot 2022-09-07 010333](https://user-images.githubusercontent.com/60604762/188696986-51c009bf-827f-445c-9540-82328a3764e5.jpg)
![Screenshot 2022-09-07 010243](https://user-images.githubusercontent.com/60604762/188696991-20305618-f71c-4e75-b873-44d1b790f3f3.jpg)

**Comment by demiglace0505** [comment]
The featured image works properly, only those images that are added using the image block are having the issues above.

**Comment by colbyfayock** [comment]
hey @demiglace0505 any interest in putting together a PR?

**Comment by demiglace0505** [comment]
Hi, sorry I haven't found a fix yet so I can't make a pr for now
