### ISSUE TITLE
CONTRIBUTING.md documentation errors

### ISSUE THREAD

**Issue by SarojWasti** [colbyfayock/next-wordpress-starter#418]
There are many typos and punctuation errors throughout the [contributing.md](https://github.com/colbyfayock/next-wordpress-starter/blob/main/CONTRIBUTING.md) doc which I would like to fix.
Like instead of `please be description`, it should be `please be descriptive`.

**Comment by colbyfayock** [comment]
thanks for the heads up but I'm not accepting minor typo fixes as contributions
