### ISSUE TITLE
ask redirect to other link based on referrer

### ISSUE THREAD

**Issue by amrjabir** [colbyfayock/next-wordpress-starter#435]
hello i'm deploying on vercel 
i need to redirect user comes from facebook to my post slug
to other domain name with the same slug

**Comment by colbyfayock** [comment]
hey @amrjabir this isnt the right space to ask broad Vercel / Next.js questions as an Issue, but here are a few things you can look into

https://nextjs.org/docs/api-reference/next/router
https://vercel.com/guides/does-vercel-support-permanent-redirects#in-application-redirects
