### ISSUE TITLE
Use GraphQL to query WordPress data

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#5]
Currently, we're using the WordPress REST API to fetch page data. This works, but we can optimize and simplify requests especially when moving into more complex features by using GraphQL queries using the WordPress GraphQL API.

## Questions
* Would this require an additional plugin or does this work "out of the box"?

**Comment by doingandlearning** [comment]
I’m going to mess around on this today.

**Comment by doingandlearning** [comment]
Here is an example from the Next repo. Looks like we need to use the Apollo client. https://github.com/vercel/next.js/tree/canary/examples/with-apollo

**Comment by colbyfayock** [comment]
sounds awesome, haven't worked with apollo before, so should be cool to see

**Comment by doingandlearning** [comment]
Is this closed with the recent merges?

**Comment by colbyfayock** [comment]
i think thats fair :) we can iteratively hit the... rest 👀

**Comment by colbyfayock** [comment]
Just closing the loop here - i wrapped up migrating everything else to GraphQL

https://github.com/colbyfayock/next-wordpress-starter/pull/30
