### ISSUE TITLE
Better meta descriptions

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#52]
I set up meta descriptions in to basic patterned values with the goal of getting _something_ in there.

It would be great to write and customize these to look a bit better. They still need to be a pattern as the use case here is that the pages would change

Future work can include a tutorial about how to add ACF or Yoast to customize this from within WP

Please propose the written solutions before doing the work

**Comment by DhrutikPatel** [comment]
Hello @colbyfayock can I do this task?

**Comment by colbyfayock** [comment]
hey @DhrutikPatel sure thing - before you start on any changes, can you present your idea here? thanks

**Comment by doingandlearning** [comment]
Hi @DhrutikPatel - how are you getting on with this? Give a shout if we can help.

**Comment by DhrutikPatel** [comment]
hello @doingandlearning, I did not understood the issue can you please explain in detail ?

**Comment by colbyfayock** [comment]
the hope for this Issue was to take the time to rewrite the meta descriptions that are included by default with this Starter

for instance, on Archive pages, we include a patterned snippet like this:
```
let metaDescription = `Read ${posts.length} posts from ${title} at ${siteTitle}.`;
```
https://github.com/colbyfayock/next-wordpress-starter/blob/master/src/templates/archive.js#L30

Allowing that pattern to work dynamically for all pages that use that template, but it's not the best description.

The hope here is to  go through the site and rewrite any of the patterns to something that is a bit more SEO friendly and enticing for people searching for a website

**Comment by DhrutikPatel** [comment]
I am getting following error while run the project using **npm run dev**

```
Module not found: Can't resolve 'public/wp-search.json'
  2 | import Fuse from 'fuse.js';
  3 |
> 4 | import searchIndex from 'public/wp-search.json';
  5 |
  6 | const searchKeys = ['slug', 'title'];
  7 |
error - ./src/hooks/use-search.js:4:0
Module not found: Can't resolve 'public/wp-search.json'
  2 | import Fuse from 'fuse.js';
  3 |
> 4 | import searchIndex from 'public/wp-search.json';
  5 |
  6 | const searchKeys = ['slug', 'title'];
  7 |
```

And no description in given on **public/wp-search.json** file in readme.md

**Comment by colbyfayock** [comment]
@DhrutikPatel have you created a local environment file that includes a wordpress host?

https://github.com/colbyfayock/next-wordpress-starter#environment

**Comment by DhrutikPatel** [comment]
> @DhrutikPatel have you created a local environment file that includes a wordpress host?
> 
> https://github.com/colbyfayock/next-wordpress-starter#environment

Yes I have created **.env.local** file and added hostname also.

**Comment by colbyfayock** [comment]
i just cloned the repo and did a fresh install and had no issues

do you have WPGraphQL installed on WordPress?

https://github.com/colbyfayock/next-wordpress-starter#requirements

can you open up a new Issue if you're still having problems as it's not relevant to this issue?
