### ISSUE TITLE
Parent / Child Page Support

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#59]
We should support the ability to have both Parent and Child pages

I'm not sure how this would currently compile, but we need to investigate that and where the path would be

If for instance, we have a Parent / Child relationship with a parent page called Docs with a slug of `docs` and a child page of Getting Started with a slug of `getting-started`, the page should be available at `/docs/getting-started`

Some ideas around this:
* Maybe by default we can provide a left or right sidebar on parent pages that have child pages with a list of all of those pages
* Do we want to add dropdowns to the navigation menu items for the first level children?
* We should have breadcrumbs on child pages that link to the top level page
* How many levels of children does wordpress support?

Please propose a solution and plan before getting started on this

**Comment by doingandlearning** [comment]
Some wonderings and ponderings :) 
>- Maybe by default we can provide a left or right sidebar on parent pages that have child pages with a list of all of those pages

I wonder if this should be driven by the menu system rather than the page system?

>- Do we want to add dropdowns to the navigation menu items for the first level children?

I wonder if these are in the page itself, a TOC at the top or bottom maybe?
>- We should have breadcrumbs on child pages that link to the top level page

I think this would be cool.
>- How many levels of children does wordpress support?

As many as you want :)

**Comment by colbyfayock** [comment]
How do menu systems work for dynamically generated parent/child relationships?

**Comment by colbyfayock** [comment]
Found I could use URIs to support page lookups and such, have a nice solution, moved the child pages to the bottom so they weren't intrusive as a sidebar

https://github.com/colbyfayock/next-wordpress-starter/pull/77
