### ISSUE TITLE
Menu support

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#7]
WordPress allows the ability to manage menus within the editor to easily make changes to navigation and other menus.

The goal of this will be to seed this functionality into the project with a starting point of making it possible to change the Navigation as a Menu

If there is no Navigation menu created, the project should work as it is (or propose a different default configuration) so that not having a Navigation Menu wouldn't break the site

If there is a Navigation Menu, that menu should be used to fill out the global site nav

**Comment by colbyfayock** [comment]
it seems like this requires a plugin to take advantage in the API

maybe this can be a tutorial for how to add it or a plugin to extend?

**Comment by doingandlearning** [comment]
Now we have GraphQL this should be fun to do.
