### ISSUE TITLE
Require full path to the WPGraphQL endpoint

### ISSUE THREAD

**Issue by jasonbahl** [colbyfayock/next-wordpress-starter#79]
WPGraphQL allows the endpoint to be filtered, and more recently even changed in the Settings page, so there's no guarantee that the endpoint will be `/graphql`. 

![Screen Shot 2020-10-23 at 11 55 55 PM](https://user-images.githubusercontent.com/1260765/97069141-4e1b9500-158b-11eb-989f-4e9faf95a2c4.png)

Instead of adding `/graphql` to the configured domain the full path should be added to the config.

https://github.com/colbyfayock/next-wordpress-starter/blob/386ecf0f840a5ea9a0a59cd270639dc902ad7056/src/lib/apollo-client.js#L14

**Comment by doingandlearning** [comment]
Oh! That is very cool - thanks for checking out the project Jason! Value any of your other WP graphql insights for things we might be missing :)

**Comment by colbyfayock** [comment]
we'll also need a fix here inside of the search index util file

https://github.com/colbyfayock/next-wordpress-starter/blob/master/plugins/util.js#L42
