### ISSUE TITLE
Pinned post support

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#8]
Content editors should be able to pin a blog post using the WordPress editor

In WordPress this feature is called "Sticky"

I've gone ahead and made the post with slug `i-love-you-buddy` sticky. If you look in the JSON response, the post that's sticky has an attribute of `sticky: true`.

http://54.243.240.9/wp-json/wp/v2/posts

You can make multiple posts sticky.

We probably will want to find the posts that are sticky within the posts array, pull them out, and append them to the top of the posts list when rendering them to the page

We should additionally add some kind of icon to identify a sticky post. Maybe a pin icon? I'm open to suggestions. The project includes `react-icons` and currently makes use of Font Awesome. We should use an icon that matches that style.

## Questions
* Should the "sticky" posts show twice? Once at the top and once in it's natural location? How does Twitter handle pinned Tweets? What does a typical WP site do?

**Comment by GuilleAngulo** [comment]
Hi again! 
I made a test and the default behaviour at Wordpress and Twitter is to put the sticky post at the top but does not repeat again at its position. Maybe is a good idea to do it this way.

Here a suggestion I made for the design 😃 (using the Font Awesome pin icon, in order to follow the other styles):


![sticky](https://user-images.githubusercontent.com/50624358/96154891-ae546c00-0ee5-11eb-80f6-380ec17e259a.png)

**Comment by GuilleAngulo** [comment]
Trying to get _sticky_ information with **wp-grapqhl plugin**, I realized that this field is not available yet. However researching a little bit I discovered that they have added this field to the development branch only few days ago as **isSticky** field: https://github.com/wp-graphql/wp-graphql/pull/1495.

**Comment by colbyfayock** [comment]
the design mockup looks great! i might even go as far as saying you might not need the text "Sticky Post" visually there, though youd probably want to have that available for screen readers

thats so strange they dont expose that with it being in the REST API. i don't understand why little things like that are different 😂 

i think the sorting makes sense for sure! didn't think about doing it that way. my only concern would have been that it would have impacted the order beyond the `isSticky` placement but if that seems like it's working i have no issues with that approach

id say we hold off until it's in the main branch, but theres no reason you can't get it prepped in a PR until then. would you mind looping back once it is in the main branch though so people dont have to figure that part out separately?

**Comment by GuilleAngulo** [comment]
Perfect, will prepare that PR then. About the text "sticky post" totally agree, I´ll leave only the pin icon and add to it an aria-label in order to make it readable for screen readers. 👍

**Comment by colbyfayock** [comment]
awesome 💪  thanks @GuilleAngulo

**Comment by colbyfayock** [comment]
Will be available in v0.14.0 https://github.com/wp-graphql/wp-graphql/pull/1513

**Comment by GuilleAngulo** [comment]
Great! I will pay attention
