### ISSUE TITLE
Trailing WORDPRESS_HOST slash breaks builds

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#83]
@colbyfayock Yes, checked just now and seems like is breaking with the trailingslash, it adds double _//._ Also this is related to #79.

![issue](https://user-images.githubusercontent.com/50624358/97354696-929d7e00-1874-11eb-81f8-36d1f6777ba4.png)

_Originally posted by @GuilleAngulo in https://github.com/colbyfayock/next-wordpress-starter/issues/50#issuecomment-717495655_

**Comment by colbyfayock** [comment]
@GuilleAngulo i can't assign it to you for some reason 😂  but here it is

**Comment by GuilleAngulo** [comment]
hahaha 👍
