### ISSUE TITLE
JSON-LD Structured data

### ISSUE THREAD

**Issue by GuilleAngulo** [colbyfayock/next-wordpress-starter#92]
Hey! So I was wondering if this would be an interesting feature for posts, to enable special search result features and enhancements. 
What do you think? 

Links:
https://developers.google.com/search/docs/guides/intro-structured-data
https://developers.google.com/search/docs/data-types/article

**Comment by colbyfayock** [comment]
@GuilleAngulo yeah for sure! i honestly though i already had a ticket for that somewhere 😂 

i believe most pages can have generalized tags with structured data right? but posts are probably the most relevant

**Comment by GuilleAngulo** [comment]
@colbyfayock yes! I think **posts**, **pages** and **index** could be a good starting point. Would be also a good practice to include on authors and categories?

Discovered this feature just now reading Google documentation: [searchbox](https://developers.google.com/search/docs/data-types/sitelinks-searchbox#example) , It's pretty cool! A search box inside google result.

I'm interested on this one, can I give a try?

**Comment by colbyfayock** [comment]
yeah for sure, all you! :)
